kind: Pod   ## type of resource we want to create in k8s cluster -- kubectl api-resources
apiVersion: v1
metadata:
  name: cka
  labels:    ## defining lables for pods is mandatory 
    group: cka-pod
spec:
  containers:
    - name: cont1
      image: nginx:latest
      ports: 
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443

--------

apiVersion: apps/v1
kind: Pod
metadata:
  name: cka
  labels:
    group: ckastudents

spec: 
  containers:
    - name: cont1 
      image: nginx:latest
      ports: 
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443 
      env: 
        - name: DB_User
          value: produser 