kind: Pod   ## type of resource we want to create in k8s cluster -- kubectl api-resources
apiVersion: v1
metadata:
  name: multi-cont-pod
  labels:    ## defining lables for pods is mandatory 
    group: cka-multi-cont
  #namesapce: prod
spec:
  containers:
    - name: cont1
      image: nginx:latest
      ports: 
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
    - name: cont2
      image: tomcat
      ports: 
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
    - name: cont3
      image: ubuntu
      command: ['sleep', '-c' , '60']