kind: Pod   ## type of resource we want to create in k8s cluster -- kubectl api-resources
apiVersion: v1
metadata:
  name: labels-selectors-pod
  labels:    ## defining lables for pods is mandatory 
    app: web
    funtion: front-end 
spec:
  containers:
    - name: cont1
      image: nginx:latest
      ports: 
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443