kind: Deployment
apiVersion: apps/v1
metadata:
  name: headless-deployment
  # labels:   not mandatory 
spec:
  selector:
    matchLabels:
      app: headless-deployment
  replicas: 3
  template:   # pod template which need to be created, which include always about the pod metadata & spec
    metadata:
      #name: test
      labels:
        app: headless-deployment
    spec:
      containers:
      - name: headless-deployment
        image: lforlinux/http-server:v1
        ports:
        - containerPort: 80